### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by mkannan22** [Jsitech/relayer#2]
Whenever I run this script on Kali 2018.3 using any selection (unicorn, sct, or powersploit) I receive the following errors:

Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/impacket-0.9.18.dev0-py2.7.egg/EGG-INFO/scripts/smbrelayx.py", line 161, in run
KeyError: 'X.X.X.X'

**Comment by Jsitech** [comment]
Could not replicate the exact error, but noticed smbrelayx and responder are not executing and i am receiving a bunch of errors. Looks like several things have changed on the recent kali linux updates. Will need to test and update. Thanks for reporting this issue. Will report back once i have everything working as it should.
